server:
  port: 8080

spring:
  datasource:
    username: root
    password: 333
    url: jdbc:mysql://localhost:3306/smbms
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.xxh.crud.entity